pragma solidity ^0.4.24;
// Define a contract 'Supplychain'
contract SupplyChain {

  // Define 'owner'
  address owner;

  // Define a variable called 'upc' for Universal Product Code (UPC)
  uint  upc;

  // Define a variable called 'sku' for Stock Keeping Unit (SKU)
  uint  sku;

  // Define a public mapping 'items' that maps the UPC to an Item.
  mapping (uint => Item) items;

  // Define a public mapping 'itemsHistory' that maps the UPC to an array of TxHash,
  // that track its journey through the supply chain -- to be sent from DApp.
  mapping (uint => string[]) itemsHistory;

  // Define enum 'State' with the following values:
  enum State
  {
    Designed,  // 0
    Approved,  // 1
    UnderProduction, //2
    Packed,     // 3
    ForSale,    // 4
    Sold,       // 5
    Shipped,    // 6
    Received,   // 7
    Purchased   // 8
    }

  State constant defaultState = State.Designed;

  // Define a struct 'Item' with the following fields:
  struct Item {
    uint    sku;  // Stock Keeping Unit (SKU)
    uint    upc; // Universal Product Code (UPC), generated by the manufacturer, goes on the package, can be verified by the Consumer
    address ownerID;  // Metamask-Ethereum address of the current owner as the product moves through 8 stages
    address originManufactureID; // Metamask-Ethereum address of the Farmer
    string  originManufactureName; // Farmer Name
    string  originManufactureInformation;  // Farmer Information
    string  originManufactureLatitude; // Farm Latitude
    string  originManufactureLongitude;  // Farm Longitude
    uint    productID;  // Product ID potentially a combination of upc + sku
    string  productNotes; // Product Notes
    uint    productPrice; // Product Price
    State   itemState;  // Product State as represented in the enum above
    address distributorID;  // Metamask-Ethereum address of the Distributor
    address retailerID; // Metamask-Ethereum address of the Retailer
    address consumerID; // Metamask-Ethereum address of the Consumer
  }

  // Define (9) events with the same 9 state values and accept 'upc' as input argument
  event Designed(uint upc);
  event Approved(uint upc);
  event UnderProduction(uint upc);
  event Packed(uint upc);
  event ForSale(uint upc);
  event Sold(uint upc);
  event Shipped(uint upc);
  event Received(uint upc);
  event Purchased(uint upc);

  // Define a modifer that checks to see if msg.sender == owner of the contract
  modifier onlyOwner() {
    require(msg.sender == owner);
    _;
  }

  // Define a modifer that verifies the Caller
  modifier verifyCaller (address _address) {
    require(msg.sender == _address);
    _;
  }

  // Define a modifier that checks if the paid amount is sufficient to cover the price
  modifier paidEnough(uint _price) {
    require(msg.value >= _price);
    _;
  }

  // Define a modifier that checks the price and refunds the remaining balance
  modifier checkValue(uint _upc) {
    _;
    uint _price = items[_upc].productPrice;
    uint amountToReturn = msg.value - _price;
    items[_upc].consumerID.transfer(amountToReturn);
  }

  // Define a modifier that checks if an item.state of a upc is Designed
  modifier designed(uint _upc) {
    require(items[_upc].itemState == State.designed);
    _;
  }

  // Define a modifier that checks if an item.state of a upc is approved
  modifier approved(uint _upc) {
    require(items[_upc].itemState == State.Approved);
    _;
  }

  // Define a modifier that checks if an item.state of a upc is UnderProduction
  modifier underProduction(uint _upc) {
    require(items[_upc].itemState == State.UnderProduction);
    _;
  }

  // Define a modifier that checks if an item.state of a upc is Packed
  modifier packed(uint _upc) {
    require(items[_upc].itemState == State.Packed);
    _;
  }

  // Define a modifier that checks if an item.state of a upc is ForSale
  modifier forSale(uint _upc) {
    require(items[_upc].itemState == State.ForSale);
    _;
  }

  // Define a modifier that checks if an item.state of a upc is Sold
  modifier sold(uint _upc) {
    require(items[_upc].itemState == State.Sold);
    _;
  }

  // Define a modifier that checks if an item.state of a upc is Shipped
  modifier shipped(uint _upc) {
    require(items[_upc].itemState == State.Shipped);
    _;
  }

  // Define a modifier that checks if an item.state of a upc is Received
  modifier received(uint _upc) {
    require(items[_upc].itemState == State.Received);
    _;
  }

  // Define a modifier that checks if an item.state of a upc is Purchased
  modifier purchased(uint _upc) {
    require(items[_upc].itemState == State.Purchased);
    _;
  }

  // In the constructor set 'owner' to the address that instantiated the contract
  // and set 'sku' to 1
  // and set 'upc' to 1
  constructor() public payable {
    owner = msg.sender;
    sku = 1;
    upc = 1;
  }

  // Define a function 'kill' if required
  function kill() public {
    if (msg.sender == owner) {
      selfdestruct(owner);
    }
  }

  // Define a function 'designItem' that allows a farmer to mark an item 'designed'
  function designItem(uint _upc, address _originManufactureID, string _originManufactureName, string _originManufactureInformation,
     string  _originManufactureLatitude, string  _originManufactureLongitude, string  _productNotes) public
  {
    // Add the new item as part of toys manufactured
    var newitem = items[_upc]; //adding a new item to the mapping
    newitem.sku = sku;
    newitem.upc = _upc;
    newitem.originManufactureID = _originManufactureID
    newitem.originManufactureName = _originManufactureName;
    newitem.originManufactureInformation = _originManufactureInformation;
    newitem.originManufactureLatitude = _originManufactureLatitude;
    newitem.originManufactureLongitude = _originManufactureLongitude;
    newitem.productNotes= _productNotes;
    newitem.itemState = State.designed;
    newitem.productID = sku+_upc;
    //newitem.productPrice ;
    // Increment sku
    sku = sku + 1;
    // Emit the appropriate event
    emit Designed(sku);
  }

  // Define a function 'approveItem' that allows a farmer to mark an item 'Approved'
  function approveItem(uint _upc) public
  // Call modifier to check if upc has passed previous supply chain stage
  designed(_upc)
  // Call modifier to verify caller of this function
  onlyOwner
  verifyCaller(owner)
  {
    // Update the appropriate fields
    items[_upc].itemState = State.Approved;
    // Emit the appropriate event
    emit Approved(sku);
  }
  // Define a function 'approveItem' that allows a farmer to mark an item 'underProduction'
  function underProductionItem(uint _upc) public
  // Call modifier to check if upc has passed previous supply chain stage
  designed(_upc) approved(_upc)
  // Call modifier to verify caller of this function
  onlyOwner
  verifyCaller(owner)
  {
    // Update the appropriate fields
    items[_upc].itemState = State.UnderProduction;
    // Emit the appropriate event
    emit UnderProduction(sku);
  }
  // Define a function 'packItem' that allows a farmer to mark an item 'Packed'
  function packItem(uint _upc) public
  // Call modifier to check if upc has passed previous supply chain stage
  designed(_upc) approved(_upc) UnderProduction(_upc)
  // Call modifier to verify caller of this function
  verifyCaller(owner)
  {
    // Update the appropriate fields
    items[_upc].itemState = State.Packed;
    // Emit the appropriate event
 emit Packed();
  }

  // Define a function 'sellItem' that allows a farmer to mark an item 'ForSale'
  function sellItem(uint _upc, uint _price) public
  // Call modifier to check if upc has passed previous supply chain stage
  designed(_upc) approved(_upc) UnderProduction(_upc), packed(_upc)
  // Call modifier to verify caller of this function
  verifyCaller(owner)
  {
    // Update the appropriate fields
    items[_upc].itemState = State.ForSale;
    // Emit the appropriate event
    emit ForSale();
  }

  // Define a function 'buyItem' that allows the disributor to mark an item 'Sold'
  // Use the above defined modifiers to check if the item is available for sale, if the buyer has paid enough,
  // and any excess ether sent is refunded back to the buyer
  function buyItem(uint _upc) public payable
    // Call modifier to check if upc has passed previous supply chain stage
    designed(_upc) approved(_upc) UnderProduction(_upc) packed(_upc)  forSale(_upc)
    // Call modifer to check if buyer has paid enough
    paidEnough(msg.value) ,
    // Call modifer to send any excess ether back to buyer
    checkValue(_upc)
    {

    // Update the appropriate fields - ownerID, distributorID, itemState
    items[_upc].ownerID = message.sender;
    items[_upc].distributorID = message.sender;
    items[_upc].itemState = State.Sold;
    // Transfer money to manufacturer

    uint256 toyCost =item[_upc].productPrice;
    address manufactureAdress = item[_upc].originManufactureID;
    require(msg.value >toyCost);

    manufactureAdress.transfer(toyCost);
    // emit the appropriate event
    emit Sold();

  }

  // Define a function 'shipItem' that allows the distributor to mark an item 'Shipped'
  // Use the above modifers to check if the item is sold
  function shipItem(uint _upc) public
    // Call modifier to check if upc has passed previous supply chain stage
    designed(_upc) approved(_upc) UnderProduction(_upc) packed(_upc)  forSale(_upc) sold(_upc)
    // Call modifier to verify caller of this function
    verifyCaller(owner)
    {
    // Update the appropriate fields
    items[_upc].itemState = State.Shipped;
    // Emit the appropriate event
    emit Shipped();
  }

  // Define a function 'receiveItem' that allows the retailer to mark an item 'Received'
  // Use the above modifiers to check if the item is shipped
  function receiveItem(uint _upc) public
    // Call modifier to check if upc has passed previous supply chain stage
    designed(_upc) approved(_upc) UnderProduction(_upc) packed(_upc)  forSale(_upc) sold(_upc) shipped(_upc)
    // Access Control List enforced by calling Smart Contract / DApp

    {
    // Update the appropriate fields - ownerID, retailerID, itemState
    items[_upc].ownerID = message.sender;
    items[_upc].retailerID = message.sender;
    items[_upc].itemState = State.Received;
    // Emit the appropriate event
    emit Received();

  }

  // Define a function 'purchaseItem' that allows the consumer to mark an item 'Purchased'
  // Use the above modifiers to check if the item is received

  function purchaseItem(uint _upc) public
    // Call modifier to check if upc has passed previous supply chain stage
    designed(_upc) approved(_upc) UnderProduction(_upc) packed(_upc)  forSale(_upc) sold(_upc) shipped(_upc)  received(_upc)
    // Access Control List enforced by calling Smart Contract / DApp
    {
    // Update the appropriate fields - ownerID, consumerID, itemState
    items[_upc].ownerID = message.sender;
    items[_upc].retailerID = message.sender;
    items[_upc].itemState = State.Received;
    // Emit the appropriate event
    emit Purchased();
  }

  // Define a function 'fetchItemBufferOne' that fetches the data
  function fetchItemBufferOne(uint _upc) public view returns
  (
  uint    itemSKU,
  uint    itemUPC,
  address ownerID,
  address originManufactureID;
  string  originManufactureName;
  string  originManufactureInformation;
  string  originManufactureLatitude;
  string  originManufactureLongitude;
  )
  {
  // Assign values to the 8 parameters

  itemSKU = items[_upc].sku;
  itemUPC = items[_upc].upc;
  ownerID = items[_upc].ownerID;
  originManufactureID = items[_upc].originManufactureID;
  originManufactureName = items[_upc].originManufactureName;
  originManufactureInformation = items[_upc].originManufactureInformation;
  originManufactureLatitude = items[_upc].originManufactureLatitude;
  originManufactureLongitude = items[_upc].originManufactureLongitude;

  return
  (
  itemSKU,
  itemUPC,
  ownerID,
  originManufactureID,
  originManufactureName,
  originManufactureInformation,
  originManufactureLatitude,
  originManufactureLongitude
  );
  }

  // Define a function 'fetchItemBufferTwo' that fetches the data
  function fetchItemBufferTwo(uint _upc) public view returns
  (
  uint    itemSKU,
  uint    itemUPC,
  uint    productID,
  string  productNotes,
  uint    productPrice,
  uint    itemState,
  address distributorID,
  address retailerID,
  address consumerID
  )
  {
    // Assign values to the 9 parameters
    itemSKU = items[_upc].sku;
    itemUPC = items[_upc].upc;
    productID = items[_upc].productID;
    productNotes = items[_upc].productNotes;
    productPrice = items[_upc].productPrice;
    itemState = items[_upc].itemState;
    distributorID = items[_upc].distributorID;
    retailerID = items[_upc].retailerID;
    consumerID = items[_upc].consumerID;

  return
  (
  itemSKU,
  itemUPC,
  productID,
  productNotes,
  productPrice,
  itemState,
  distributorID,
  retailerID,
  consumerID
  );
  }
}
